<?php
	$beltList = array(
	'0.00' => array('Group' => 'Little Ninja',	'Rank_Name' => 'White Belt', 		'Image_Loc' => 'W.png',		'Req_Visits' => 1,		'Req_Months' => 1),
	'1.00' => array('Group' => 'Children',		'Rank_Name' => 'White Belt', 		'Image_Loc' => 'W.png',		'Req_Visits' => 8,		'Req_Months' => 1),
	'1.01' => array('Group' => 'Children',		'Rank_Name' => '1 Yellow Stripe', 	'Image_Loc' => 'W1Y.png',	'Req_Visits' => 8,		'Req_Months' => 1),
	'1.02' => array('Group' => 'Children',		'Rank_Name' => '2 Yellow Stripes',	'Image_Loc' => 'W2Y.png',	'Req_Visits' => 12,		'Req_Months' => 1),
	'1.03' => array('Group' => 'Children',		'Rank_Name' => 'Yellow Belt', 		'Image_Loc' => 'Y.png',		'Req_Visits' => 12,		'Req_Months' => 1),
	'1.04' => array('Group' => 'Children',		'Rank_Name' => 'Purple Stripe', 	'Image_Loc' => 'Y1P.png',	'Req_Visits' => 12,		'Req_Months' => 1),
	'1.05' => array('Group' => 'Children',		'Rank_Name' => '2 Purple Stripes',	'Image_Loc' => 'Y2P.png',	'Req_Visits' => 18,		'Req_Months' => 1),
	'1.06' => array('Group' => 'Children',		'Rank_Name' => 'Purple Belt', 		'Image_Loc' => 'P.png',		'Req_Visits' => 24,		'Req_Months' => 2),
	'1.07' => array('Group' => 'Children',		'Rank_Name' => '1 Blue Stripe', 	'Image_Loc' => 'P1Bl.png',	'Req_Visits' => 24,		'Req_Months' => 2),
	'1.08' => array('Group' => 'Children',		'Rank_Name' => '2 Blue Stripes', 	'Image_Loc' => 'P2Bl.png',	'Req_Visits' => 24,		'Req_Months' => 2),
	'1.09' => array('Group' => 'Children',		'Rank_Name' => 'Blue Belt', 		'Image_Loc' => 'Bl.png',	'Req_Visits' => 24,		'Req_Months' => 2),
	'1.10' => array('Group' => 'Children',		'Rank_Name' => '1 Green Stripe', 	'Image_Loc' => 'Bl1G.png',	'Req_Visits' => 24,		'Req_Months' => 2),
	'1.11' => array('Group' => 'Children',		'Rank_Name' => '2 Green Stripes', 	'Image_Loc' => 'Bl2G.png',	'Req_Visits' => 28,		'Req_Months' => 3),
	'1.12' => array('Group' => 'Children',		'Rank_Name' => 'Green Belt', 		'Image_Loc' => 'G.png',		'Req_Visits' => 28,		'Req_Months' => 3),
	'1.13' => array('Group' => 'Children',		'Rank_Name' => '1 Brown Stripe', 	'Image_Loc' => 'G1Br.png',	'Req_Visits' => 28,		'Req_Months' => 3),
	'1.14' => array('Group' => 'Children',		'Rank_Name' => '2 Brown Stripes', 	'Image_Loc' => 'G2Br.png',	'Req_Visits' => 28,		'Req_Months' => 3),
	'1.15' => array('Group' => 'Children',		'Rank_Name' => '3 Brown Stripes', 	'Image_Loc' => 'G3Br.png',	'Req_Visits' => 28,		'Req_Months' => 3),
	'1.16' => array('Group' => 'Children',		'Rank_Name' => '4 Brown Stripes', 	'Image_Loc' => 'G4Br.png',	'Req_Visits' => 45,		'Req_Months' => 5),
	'1.17' => array('Group' => 'Children',		'Rank_Name' => 'Brown Belt', 		'Image_Loc' => 'Br.png',	'Req_Visits' => 45,		'Req_Months' => 5),
	'1.18' => array('Group' => 'Children',		'Rank_Name' => '1 Black Stripe', 	'Image_Loc' => 'Br1Bk.png',	'Req_Visits' => 45,		'Req_Months' => 5),
	'1.19' => array('Group' => 'Children',		'Rank_Name' => '2 Black Stripes', 	'Image_Loc' => 'Br2Bk.png',	'Req_Visits' => 54,		'Req_Months' => 6),
	'1.20' => array('Group' => 'Children',		'Rank_Name' => '3 Black Stripes', 	'Image_Loc' => 'Br3Bk.png',	'Req_Visits' => 54,		'Req_Months' => 6),
	'1.21' => array('Group' => 'Children',		'Rank_Name' => '4 Black Stripes', 	'Image_Loc' => 'Br4Bk.png',	'Req_Visits' => 54,		'Req_Months' => 6),
	'1.22' => array('Group' => 'Children',		'Rank_Name' => 'Black Belt', 		'Image_Loc' => 'Bk.png',	'Req_Visits' => 108,	'Req_Months' => 9),
	'1.23' => array('Group' => 'Children',		'Rank_Name' => 'Shodan', 			'Image_Loc' => 'Bk1R.png',	'Req_Visits' => 260,	'Req_Months' => 24),
	'2.00' => array('Group' => 'Adult',			'Rank_Name' => 'White Belt', 		'Image_Loc' => 'W.png',		'Req_Visits' => 24,		'Req_Months' => 3),
	'2.01' => array('Group' => 'Adult',			'Rank_Name' => '1 Green Stripe', 	'Image_Loc' => 'W1G.png',	'Req_Visits' => 36,		'Req_Months' => 3),
	'2.02' => array('Group' => 'Adult',			'Rank_Name' => '2 Green Stripes',	'Image_Loc' => 'W2G.png',	'Req_Visits' => 36,		'Req_Months' => 3),
	'2.03' => array('Group' => 'Adult',			'Rank_Name' => 'Green Belt', 		'Image_Loc' => 'G.png',		'Req_Visits' => 54,		'Req_Months' => 3),
	'2.04' => array('Group' => 'Adult',			'Rank_Name' => '1 Brown Stripe', 	'Image_Loc' => 'G1Br.png',	'Req_Visits' => 54,		'Req_Months' => 3),
	'2.05' => array('Group' => 'Adult',			'Rank_Name' => '2 Brown Stripes', 	'Image_Loc' => 'G2Br.png',	'Req_Visits' => 90,		'Req_Months' => 4),
	'2.06' => array('Group' => 'Adult',			'Rank_Name' => 'Brown Belt', 		'Image_Loc' => 'Br.png',	'Req_Visits' => 90,		'Req_Months' => 4),
	'2.07' => array('Group' => 'Adult',			'Rank_Name' => '1 Black Stripe', 	'Image_Loc' => 'Br1Bk.png',	'Req_Visits' => 108,	'Req_Months' => 6),
	'2.08' => array('Group' => 'Adult',			'Rank_Name' => '2 Black Stripes',	'Image_Loc' => 'Br2Bk.png',	'Req_Visits' => 108,	'Req_Months' => 6),
	'2.09' => array('Group' => 'Adult',			'Rank_Name' => 'Black Belt', 		'Image_Loc' => 'Bk.png',	'Req_Visits' => 108,	'Req_Months' => 9),
	'2.10' => array('Group' => 'Adult',			'Rank_Name' => 'Shodan', 			'Image_Loc' => 'Bk1R.png',	'Req_Visits' => 260,	'Req_Months' => 24),
	'2.11' => array('Group' => 'Adult',			'Rank_Name' => 'Nidan', 			'Image_Loc' => 'Bk2R.png',	'Req_Visits' => 390,	'Req_Months' => 36),
	'2.12' => array('Group' => 'Adult',			'Rank_Name' => 'Sandan', 			'Image_Loc' => 'Bk3R.png',	'Req_Visits' => 520,	'Req_Months' => 48),
	'2.13' => array('Group' => 'Adult',			'Rank_Name' => 'Yondan', 			'Image_Loc' => 'Bk4R.png',	'Req_Visits' => 650,	'Req_Months' => 60),
	'2.14' => array('Group' => 'Adult',			'Rank_Name' => 'Godan', 			'Image_Loc' => 'Go.png',	'Req_Visits' => 780,	'Req_Months' => 72),
	'2.15' => array('Group' => 'Adult',			'Rank_Name' => 'Rokudan', 			'Image_Loc' => 'Ro.png',	'Req_Visits' => 910,	'Req_Months' => 84),
	'2.16' => array('Group' => 'Adult',			'Rank_Name' => 'Shichidan', 		'Image_Loc' => 'Sh.png',	'Req_Visits' => 1040,	'Req_Months' => 96),
	'2.17' => array('Group' => 'Adult',			'Rank_Name' => 'Hachidan',	 		'Image_Loc' => 'Ha.png',	'Req_Visits' => 1170,	'Req_Months' => 108),
	'9.99' => array('Group' => 'Quit',			'Rank_Name' => 'Quit',				'Image_Loc' => 'W.png',		'Req_Visits' => 999,	'Req_Months' => 999));
?>